display_name: TodartTxt
package_name: todart-txt
maintainer:
  name: galets
  email: todart@x11.work
priority: optional
section: utils
installed_size: 40000
essential: false
icon: branding/todart-icon.png
generic_name: Todo.txt Task Manager
keywords:
  - todo
  - todo.txt
  - tasks
  - productivity
categories:
  - Office
  - Utility
startup_notify: true
supported_mime_type:
  - text/plain
